### ISSUE TITLE
license error occurs when download the dataset

### ISSUE THREAD

**Issue by XiaoshuiHuang** [EPFL-VILAB/omnidata#11]
Hi authors,
    I got an error when I run the download script `omnitools.download rgb depth mask_valid --components all --subset fullplus   --dest ./omnidata_starter_dataset/   --connections_total 40 --agree` , the error information shows below. Can you help me to solve this issue?

/mnt/x/anaconda3/envs/unipoint/lib/python3.9/site-packages/fastcore/docscrape.py:225: UserWarning: potentially wrong underline length...
Downloads Omnidata starter dataset.
--- in
Downloads Omnidata starter dataset.
---...
  else: warn(msg)
[HEADER] -------------------------------------
[HEADER] From SERVERS: (using checksum validation: False)
[HEADER]     https://datasets.epfl.ch/omnidata//links.txt
[HEADER]     https://datasets.epfl.ch/taskonomy//links.txt
[HEADER]
[HEADER] Data parameters: (what to download)
[HEADER]     Domains    = ['rgb', 'depth', 'mask_valid']
[HEADER]     Components = ['all']
[HEADER]     Subset     = fullplus
[HEADER]     Split      = all
[HEADER]
[HEADER] Data locations:
[HEADER]     Dataset (extracted)      = ./omnidata_starter_dataset/
[HEADER]     Compressed files         = compressed/
[HEADER] -------------------------------------

[LICENSE] Before continuing the download, please review the terms of use for each of the following component datasets:
Traceback (most recent call last):
  File "/mnt/x/anaconda3/envs/unipoint/bin/omnitools.download", line 8, in <module>
    sys.exit(download())
  File "/mnt/x/anaconda3/envs/unipoint/lib/python3.9/site-packages/fastcore/script.py", line 113, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "/mnt/x/anaconda3/envs/unipoint/lib/python3.9/site-packages/omnidata_tools/dataset/download.py", line 260, in download
    licenses_clickthrough(components, require_prompt=not agree_all, component_to_license=component_to_license, email=email, name=name)
  File "/mnt/x/anaconda3/envs/unipoint/lib/python3.9/site-packages/omnidata_tools/dataset/download.py", line 74, in licenses_clickthrough
    license(f"    {bcolors.WARNING}{component}{bcolors.ENDC}: \x1B]8;;{component_to_license[component]}\x1B\\{component_to_license[component]}\x1B]8;;\x1B\\")
KeyError: 'all'

**Comment by XiaoshuiHuang** [comment]
When I remove the parameter "componnets" and use the following script `omnitools.download rgb depth mask_valid  --subset fullplus   --dest ./omnidata_starter_dataset/   --connections_total 40 --agree_all --name xxx --email xxx@gmail.com`, the error shows below. 

```urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1129)>```

Do you have any ideas about this error?

**Comment by alexsax** [comment]
Hi!

Sorry about the delay, we were traveling for CVPR. With the first command you posted, I also get the license issue. I should probably remove the 'all' option and make people agree to the individual licenses, but looks like you figured out a good workaround. 

As for the second command, I'm unable to reproduce this issue. Looks like it could be a library [version](https://stackoverflow.com/questions/32115607/python-3-4-ssl-error-urlopen-error-eof-occurred-in-violation-of-protocol-ssl-c) problem. Do you still have this error?

**Comment by XiaoshuiHuang** [comment]
Hi,
    The error is still there when I run the download script again.  Maybe the error comes from aria2, because we do not have the sudo permission in our university server. Is there possible to download the data without sudo library install?

Kind regards
Xiaoshui

**Comment by alexsax** [comment]
There is a links.txt file that you could combine with wget or curl, but why not just use [aria2 from conda](https://anaconda.org/bioconda/aria2)? That shouldn’t require sudo :)

**Comment by XiaoshuiHuang** [comment]
I tried conda version. I got another errors. See the error screenshot below:
<img width="952" alt="image" src="https://user-images.githubusercontent.com/13249163/177456855-f295352c-85e7-4a54-b043-9bc8d6924e59.png">

**Comment by alexsax** [comment]
Hm3d is not yet supported fully, so some domains might not work. @roman-bachmann can we remove non-working domains from hm3d?

@XiaoshuiHuang try others first, maybe?

**Comment by XiaoshuiHuang** [comment]
Thanks for your replying. I tried to only download Taskonomy and got similar errors "uncaught error".

**Comment by XiaoshuiHuang** [comment]
Hi authors,
    Today, I bought a new computer with `sudo` permission and tried to download the dataset strictly following your instructions. I got the same error "urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>".  Could you check whether the dataset is still available to be downloaded?

Thanks

**Comment by alexsax** [comment]
@XiaoshuiHuang Apologies for downloading being so difficult. I'm not seeing the servers down right now:  
![image](https://user-images.githubusercontent.com/5157485/178786422-e7b4986d-9df9-4c0f-8ad2-689c28050224.png)
Could this be a firewall issue?

Here is some other information that might be important:
1) mask_valid: I'd recommend not using these, and we should probably remove them altogether. The best way to get the mask is to just take all the depths that are != (uint16) -1. mask_valid is simply a small minpool (either 3x3 or 5x5 on top of this) to also remove border areas
2) Hypersim: I think that the hypersim labels have a small misalignment issue due to the very nonstandard K matrix used in hypersim. We're working to fix that and it should be done in the next week or so.
3) If you don't want to use the downloader but would rather do the downloading (and unzipping) yourself, you can use the link files printed out from the dataloader. Currently, the files are
```
[HEADER] From SERVERS: (using checksum validation: False)
[HEADER]     https://datasets.epfl.ch/omnidata//links.txt
[HEADER]     https://datasets.epfl.ch/taskonomy//links.txt
```

**Comment by XiaoshuiHuang** [comment]
Thanks for your further information. For the issues, I am still not sure of the reasons. Personally, I do not use any firewall. However, I tried some links from "https://datasets.epfl.ch/omnidata//links.txt", they work very well. I will write my own python script to download the data.

**Comment by puyiwen** [comment]
> @XiaoshuiHuang为下载如此困难而道歉。我现在没有看到服务器停机： 这可能是防火墙问题吗？ ![图片](https://user-images.githubusercontent.com/5157485/178786422-e7b4986d-9df9-4c0f-8ad2-689c28050224.png)
> 
> 以下是一些可能很重要的其他信息：
> 
> 1. mask_valid：我建议不要使用这些，我们可能应该完全删除它们。获得蒙版的最佳方法是只取所有深度为 != (uint16) -1。mask_valid 只是一个小的 minpool（在此之上是 3x3 或 5x5），也可以删除边界区域
> 2. Hypersim：我认为由于 hypersim 中使用的非常非标准的 K 矩阵，hypersim 标签有一个小的错位问题。我们正在努力解决这个问题，应该在下周左右完成。
> 3. 如果您不想使用下载器而是想自己进行下载（和解压缩），您可以使用从数据加载器打印出来的链接文件。目前，文件是
> 
> ```
> [HEADER] From SERVERS: (using checksum validation: False)
> [HEADER]     https://datasets.epfl.ch/omnidata//links.txt
> [HEADER]     https://datasets.epfl.ch/taskonomy//links.txt
> ```

hi,may I use your name and email to download the dataset?

**Comment by alexsax** [comment]
Great!
