### ISSUE TITLE
Output normal vector not normalized

### ISSUE THREAD

**Issue by stalkerrush** [EPFL-VILAB/omnidata#14]
Hi,

Thanks for releasing this great work. To get the real normal vectors from the output normal images, I do normal = (normal_image - 0.5) * 2, but the output after this transform does not seem to have a norm of 1. Is this expected? Or is it the community standard that surface normal is not a unit vector?

**Comment by alexsax** [comment]
Hi @stalkerrush, do you mean outputs from the annotator, or the pretrained models? The annotator should have outputs that are 1 or close to 1, but just in case way we apply normalization anyway during training :)

**Comment by stalkerrush** [comment]
Hi @alexsax , thanks for the reply. I was actually talking about the pretrained model inference with your demo code. It seems that if I load the normal from the saved images with normal = (normal_image/255 - 0.5) * 2, it does not lead to a unit normal. I just want to know whether it's because I did the conversion in the wrong way or it's actually expected.

**Comment by alexsax** [comment]
Hi @stalkerrush, you did it correctly! The output isn’t normalized. We train with both an L1 loss and a cos angle loss and we only apply normalization in the cosine loss [here](https://github.com/EPFL-VILAB/omnidata/blob/fe7a0ad247e254f5123604890704d708e8aa3127/paper_code/losses/masked_losses.py#L14)
