### ISSUE TITLE
What if I put the 512*512 image to this model...

### ISSUE THREAD

**Issue by VivianGemLee** [EPFL-VILAB/omnidata#17]
Thank you for this wonderful work and it really helps me alot!
I have a question here: my images are 512 resolution and I want the 512 resulution normal map. I think if I just simply interpolate the output normal map from 384 resolution to 512 resolution will cause a huge error since the normal is very sensitive. So i'm wondering if I can just put the 512 images into the model, will I get a wrong normal map? I compared them by visualization and I cant figure out...

**Comment by alexsax** [comment]
You can use 512x512 images, or you can resize using nearest neighbor interpolation: both should work!
