### ISSUE TITLE
About the normal coordinate...

### ISSUE THREAD

**Issue by VivianGemLee** [EPFL-VILAB/omnidata#18]
I have a question about how to determine the predicted normal coordinate system for any input rgb image (my own)?
I want to unfold a rectangular patch in the picture to a plane through the predicted normal vector to eliminate the distortion caused by perspective.
I would appreciate it if you could help me.

**Comment by alexsax** [comment]
Sure, the normals are defined in the local camera coordinates—there is no perspective projection of the normals and the color map is in #6
