### ISSUE TITLE
some question about image scale

### ISSUE THREAD

**Issue by LiXinghui-666** [EPFL-VILAB/omnidata#21]
Hello. I want to know when I run this model on Scannet, the image resolution of the Scannet data set is 640 x 480, which is different from the aspect ratio of the output resolution of ominidata. How can I handle the resolution problem so that the depth map and the RGB image are pixel-by-pixel corresponding? In a word, I want to have a processed depth map size of 640 x 480 and correspond pixel-by-pixel to the original rgb image.Can you give me some advance, thanks!

**Comment by reconlabs-sergio** [comment]
I have the same question. Since you closed the issue, what was the solution? Does this work out of the box?
