### ISSUE TITLE
how to download omnidata_dpt_depth_v2.ckpt file?

### ISSUE THREAD

**Issue by saiedg** [EPFL-VILAB/omnidata#22]
Hi! How do I download the version 2 pretrained models for Omnidata Normal and Omnidata Depth? I followed the instructions but I get error 'No such file or directory' when typing "sh ./tools/download_depth_models.sh" in termal.

<img width="877" alt="Screen Shot 2022-10-20 at 4 05 12 PM" src="https://user-images.githubusercontent.com/1972987/196986376-af4e2bbb-bbbd-40f3-b43a-05f249c1885f.png">

**Comment by Ainaz99** [comment]
Hi @saiedg !

I think the scripts have been relocated and we forgot to update the readme. 
You can download them by running the scripts in here: https://github.com/EPFL-VILAB/omnidata/tree/main/omnidata_tools/torch/tools.

Let me know if this didn't solve your issue.

**Comment by LownyCGI** [comment]
Hi @Ainaz99 !

This command makes tmp files

![image](https://user-images.githubusercontent.com/36165420/211155305-3be8d76d-47af-448c-b962-b50bb292ee87.png)


![image](https://user-images.githubusercontent.com/36165420/211155672-5f56d372-f349-4c5f-a1ee-00a0c44f99b7.png)
