### ISSUE TITLE
download pretrained models

### ISSUE THREAD

**Issue by yxt7979** [EPFL-VILAB/omnidata#30]
Hi, worderful work! I'd like to download the pretrained work using `gdown https://drive.google.com/uc?id=1wNxVO4vVbDEMEpnAi_jwQObf2MFodcBR -O ./pretrained_models/ # omnidata normals (v2)` but failed, could you please update the links ~ thanks a lot!

**Comment by alexsax** [comment]
Try adding `&confirm=t'`: so `gdown '1wNxVO4vVbDEMEpnAi_jwQObf2MFodcBR&confirm=t'`
I'll update the script, thanks for pointing this out!
