### ISSUE TITLE
How to install pre-trained weights from windows 10

### ISSUE THREAD

**Issue by csitaula** [EPFL-VILAB/omnidata#36]
I tried to download the pre-trained weights, but it requires sh.....
I use windows 10, how to download it from here?
I am sorry if it is a minor issue.

Thank you.

**Comment by alexsax** [comment]
Hi @csitaula, good question. The pretrained weights are stored in Google drive, so you can just download them using your favorite web browser. The necessary urls are located inside the download scripts (last 2 lines of both).
