### ISSUE TITLE
Can't download semantic data.

### ISSUE THREAD

**Issue by HLinChen** [EPFL-VILAB/omnidata#40]
When I want to download semantic data using following commands, I get nothing.
```
omnitools.download segm     --components taskonomy replica hypersim    --subset fullplus     --dest ./omnidata/     --name xx --email xxx --agree_all
```
<img width="991" alt="image" src="https://user-images.githubusercontent.com/37725241/222342290-b63ae5a2-9390-452b-9b94-aea7157bd683.png">

**Comment by janbechtold** [comment]
I have the same issue.

**Comment by alexsax** [comment]
There are different types of segmentation--semantic, unsupervised 2d (normalized cuts), and unsupervised 2.5d (cuts on RGB + Depth + Normals). 

The keys should be `semantic`, `segment_unsup2d`, and `segment_unsup25d`, respectively.

There was a typo in the readme--sorry about that!
