### ISSUE TITLE
Pose consistency in image sequences

### ISSUE THREAD

**Issue by VitorGuizilini-TRI** [EPFL-VILAB/omnidata#46]
Hi, I am trying to reconstruct sequences using a global frame of reference, but it seems like there is a lot of misalignment between certain samples.  Can you explain a little more how the "point" and "view" system works? 

My questions is whether I can assume that all images from the same sequence (i.e., folder) follow a global frame of reference in the stored poses, so I could in principle recover the entire scene by reconstructing from all poses at the same time. It seems like that is the case for some images, but not for others (sometimes I get perfect alignment, and sometimes they don't align at all).  

Thank you!

**Comment by alexsax** [comment]
For each building, we sample `points` on the mesh. Then we check which cameras have line-of-sight to the point. For each combination of building, point, visible camera, we call this a (building, point, view) triplet.

The R, T, K matrices returned by the dataloader should be in a building-wide global coordinate frame. For which buildings, points, and views are you seeing a misalignment? Are you seeing this issue with the dataloader provided [here](https://github.com/EPFL-VILAB/omnidata/tree/main/omnidata_tools/torch/dataloader)?

**Comment by VitorGuizilini-TRI** [comment]
Never mind, I found the issue here, it's all good now!  Thanks!
