### ISSUE TITLE
Failed to retrieve pretrained models

### ISSUE THREAD

**Issue by dengnianchen** [EPFL-VILAB/omnidata#52]
Hi!
I tried to download the pretrained models using the shell script ./tools/download_depth_models.sh but failed with the following error:
```
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1UxUDbEygQ-CMBjRKACw_Xdj4RkDjirB5&confirm=t 

Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1Jrh-bRnJEjyMCS7f-WsaFlccfPjJPPHI&confirm=t 
```

I also tried ./tools/download_surface_normal_models.sh and got a similar error:

```
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1iJjV9rkdeLvsTU9x3Vx8vwZUg-sSQ9nm&confirm=t 

Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1wNxVO4vVbDEMEpnAi_jwQObf2MFodcBR&confirm=t 
```

It seems the link is expired or some access control is wrongly configured?

Is there another way to download these models?

Thanks!

**Comment by ventusff** [comment]
For some reason `gdown` is unable to download the links from google drive.
In my case, you can just download the pretrained weights via browser with your **logged in** google account.

The google drive links provided in download_depth_models.sh are:
- https://drive.google.com/uc?id=1UxUDbEygQ-CMBjRKACw_Xdj4RkDjirB5&confirm=t
- https://drive.google.com/uc?id=1Jrh-bRnJEjyMCS7f-WsaFlccfPjJPPHI&confirm=t

And in download_surface_normal_models.sh:
- https://drive.google.com/uc?id=1iJjV9rkdeLvsTU9x3Vx8vwZUg-sSQ9nm&confirm=t
- https://drive.google.com/uc?id=1wNxVO4vVbDEMEpnAi_jwQObf2MFodcBR&confirm=t

You should download them into `omnidata_tools/torch/pretrained_models` directory.

**Comment by hermannsblum** [comment]
@alexsax Any chance you can host a mirror outside of gdrive? E.g. on zenodo.org? `gdown` not working makes it very annoying to automatically install anything that is dependent on omnidata...

**Comment by alexsax** [comment]
@hermannsblum great suggestion, thanks. This is a pain point, even when I want to use my own models.

I uploaded the models to zenodo and updated the scripts. Let me know if this doesn't work :)
