### ISSUE TITLE
download depth data for training 

### ISSUE THREAD

**Issue by icoz69** [EPFL-VILAB/omnidata#8]
hello, I was trying download depth data by running:
`omnitools.download rgb depth mask_valid --components replica --subset fullplus   --dest ./omnidata_starter_dataset/   --connections_total 40 --agree_all --name XXX --email XXX`
However, there is only rgb/ and mask_valid/ in omnidata_starter_dataset/ . Same for other datasets. And by the way, do I need  other post-processing to use these data for depth estimation training with omnidata_tools/torch/train_depth.py ?

**Comment by alexsax** [comment]
Hi--sorry for the delay!

There are two types of depth in Omnidata. One, `depth_zbuffer` is the distance from the optical plane. The other, `depth_euclidean` is the distance from the camera center. So you need to specify one of thost.

As for the second question: nope! you should be able to use that script as-is

**Comment by puyiwen** [comment]
> 您好，我正在尝试通过运行下载深度数据： `omnitools.download rgb depth mask_valid --components replica --subset fullplus --dest ./omnidata_starter_dataset/ --connections_total 40 --agree_all --name XXX --email XXX` 但是，omnidata_starter_dataset/ 中只有 rgb/ 和 mask_valid/ 。其他数据集也一样。顺便说一句，我是否需要其他后处理才能将这些数据用于使用 omnidata_tools/torch/train_depth.py 进行深度估计训练？

Hi,I don't know what mask_valid dataset does? Do I need to use this for depth estimation training?
